// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PocKafka.Infrastructure.Kafka.Models
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Extras : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""Extras"",""namespace"":""PocKafka.Infrastructure.Kafka.Models"",""fields"":[{""name"":""clientId"",""doc"":""Client ID."",""type"":""string""},{""name"":""licensePlate"",""doc"":""License plate."",""type"":""string""},{""name"":""vin"",""doc"":""Vehicle Identification Number (VIN, in portuguese, Chassi)."",""type"":""string""}]}");
		/// <summary>
		/// Client ID.
		/// </summary>
		private string _clientId;
		/// <summary>
		/// License plate.
		/// </summary>
		private string _licensePlate;
		/// <summary>
		/// Vehicle Identification Number (VIN, in portuguese, Chassi).
		/// </summary>
		private string _vin;
		public virtual Schema Schema
		{
			get
			{
				return Extras._SCHEMA;
			}
		}
		/// <summary>
		/// Client ID.
		/// </summary>
		public string clientId
		{
			get
			{
				return this._clientId;
			}
			set
			{
				this._clientId = value;
			}
		}
		/// <summary>
		/// License plate.
		/// </summary>
		public string licensePlate
		{
			get
			{
				return this._licensePlate;
			}
			set
			{
				this._licensePlate = value;
			}
		}
		/// <summary>
		/// Vehicle Identification Number (VIN, in portuguese, Chassi).
		/// </summary>
		public string vin
		{
			get
			{
				return this._vin;
			}
			set
			{
				this._vin = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.clientId;
			case 1: return this.licensePlate;
			case 2: return this.vin;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.clientId = (System.String)fieldValue; break;
			case 1: this.licensePlate = (System.String)fieldValue; break;
			case 2: this.vin = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
